# Dockerfile.nginx
FROM nginx:alpine

LABEL maintainer="tu@correo.com"

# 1. Instala herramientas
RUN apk add --no-cache openssl certbot

# 2. Copia el entrypoint
COPY nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh
RUN chmod +x /usr/local/bin/nginx-entrypoint.sh

# 3. Copia tu conf de Nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["/usr/local/bin/nginx-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
