# Generated by Django 5.1.7 on 2025-06-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload_enviado",
                    models.JSONField(help_text="Payload enviado al servicio SSN"),
                ),
                (
                    "respuesta",
                    models.JSONField(help_text="Respuesta recibida del servicio SSN"),
                ),
                (
                    "status_http",
                    models.PositiveIntegerField(
                        help_text="Código HTTP de la respuesta"
                    ),
                ),
                (
                    "es_error",
                    models.BooleanField(
                        default=False, help_text="Indica si la respuesta fue un error"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        help_text="Solicitud asociada a esta respuesta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="operaciones.baserequestmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Solicitud",
                "verbose_name_plural": "Respuestas de Solicitud",
                "db_table": "db_respuestas_solicitud",
                "ordering": ["-created_at"],
            },
        ),
    ]
