# Generated by Django 5.1.7 on 2025-07-02 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0002_solicitudresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baserequestmodel",
            name="operaciones",
        ),
        migrations.AlterField(
            model_name="baserequestmodel",
            name="cronograma",
            field=models.CharField(
                help_text="Periodo del cronograma (YYYY-MM)",
                max_length=7,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(7)],
            ),
        ),
    ]
