# Generated by Django 5.1.7 on 2025-07-04 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0003_remove_baserequestmodel_operaciones_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolicitudResponse",
        ),
    ]
