# Generated by Django 5.1.7 on 2025-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0004_delete_solicitudresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="bic",
            field=models.CharField(help_text="Código BIC (Bancos)", max_length=12),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="cdf",
            field=models.CharField(
                help_text="Código CDF (Certificado del Depósito a Plazo Fijo)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="codigo_titulo",
            field=models.CharField(
                blank=True, help_text="Código del título", max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="tasa",
            field=models.DecimalField(
                decimal_places=3, help_text="Valor de la tasa", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="tipo_pf",
            field=models.CharField(help_text="Tipo de depósito", max_length=3),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="tipo_tasa",
            field=models.CharField(
                choices=[("F", "Fija"), ("V", "Variable")],
                help_text="F si es Fija, V si es Variable",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="titulo_deuda",
            field=models.BooleanField(
                help_text="Indica si fue concretado con un Título de Deuda Pública"
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="valor_nominal_nacional",
            field=models.DecimalField(
                decimal_places=0, help_text="Valor nominal nacional", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="plazofijooperacion",
            name="valor_nominal_origen",
            field=models.DecimalField(
                decimal_places=0, help_text="Valor nominal origen", max_digits=10
            ),
        ),
    ]
