# Generated by Django 5.1.7 on 2025-07-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0007_chequepagodiferidostock_inversionstock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plazofijostock",
            name="valor_nominal_nacional",
        ),
        migrations.AlterField(
            model_name="plazofijostock",
            name="valor_nominal_origen",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Valor nominal en moneda origen",
                max_digits=10,
                null=True,
            ),
        ),
    ]
