# Generated by Django 5.1.7 on 2025-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_remove_plazofijostock_valor_nominal_nacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequepagodiferidostock',
            name='con_cotizacion',
        ),
        migrations.RemoveField(
            model_name='chequepagodiferidostock',
            name='emisor_art_ret',
        ),
        migrations.RemoveField(
            model_name='chequepagodiferidostock',
            name='emisor_grupo_economico',
        ),
        migrations.RemoveField(
            model_name='chequepagodiferidostock',
            name='tipo_valuacion',
        ),
        migrations.RemoveField(
            model_name='plazofijostock',
            name='con_cotizacion',
        ),
        migrations.RemoveField(
            model_name='plazofijostock',
            name='emisor_art_ret',
        ),
        migrations.RemoveField(
            model_name='plazofijostock',
            name='tipo_valuacion',
        ),
        migrations.AddField(
            model_name='chequepagodiferidostock',
            name='grupo_economico',
            field=models.BooleanField(default=False, help_text='Emisor pertenece a grupo económico (1: Sí, 0: No)'),
        ),
        migrations.AddField(
            model_name='plazofijostock',
            name='valor_nominal_nacional',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Valor nominal en Pesos Argentinos', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chequepagodiferidostock',
            name='en_custodia',
            field=models.BooleanField(default=True, help_text='Indicador en custodia (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='chequepagodiferidostock',
            name='tipo',
            field=models.CharField(choices=[('I', 'Inversión'), ('P', 'Plazo Fijo'), ('C', 'Cheque Pago Diferido')], help_text='Tipo de stock mensual', max_length=1),
        ),
        migrations.AlterField(
            model_name='chequepagodiferidostock',
            name='tipo_tasa',
            field=models.CharField(choices=[('F', 'Fija'), ('V', 'Variable')], help_text='F si es Fija, V si es Variable', max_length=1),
        ),
        migrations.AlterField(
            model_name='chequepagodiferidostock',
            name='valor_contable',
            field=models.DecimalField(decimal_places=0, help_text='Valor contable', max_digits=14),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='emisor_art_ret',
            field=models.BooleanField(default=False, help_text='Emisor ART/RET (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='emisor_grupo_economico',
            field=models.BooleanField(default=False, help_text='Emisor pertenece a grupo económico (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='en_custodia',
            field=models.BooleanField(default=True, help_text='Indicador en custodia (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='precio_pase_vt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de pase a VT', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='prevision_desvalorizacion',
            field=models.DecimalField(decimal_places=0, help_text='Previsión desvalorización', max_digits=14),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='tipo',
            field=models.CharField(choices=[('I', 'Inversión'), ('P', 'Plazo Fijo'), ('C', 'Cheque Pago Diferido')], help_text='Tipo de stock mensual', max_length=1),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='valor_contable',
            field=models.DecimalField(decimal_places=0, help_text='Valor contable', max_digits=14),
        ),
        migrations.AlterField(
            model_name='inversionstock',
            name='valor_financiero',
            field=models.DecimalField(decimal_places=0, help_text='Valor financiero', max_digits=14),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='codigo_titulo',
            field=models.CharField(blank=True, help_text='Código de título público', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='emisor_grupo_economico',
            field=models.BooleanField(default=False, help_text='Emisor pertenece a grupo económico (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='en_custodia',
            field=models.BooleanField(default=True, help_text='Indicador en custodia (1: Sí, 0: No)'),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='tipo',
            field=models.CharField(choices=[('I', 'Inversión'), ('P', 'Plazo Fijo'), ('C', 'Cheque Pago Diferido')], help_text='Tipo de stock mensual', max_length=1),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='tipo_tasa',
            field=models.CharField(choices=[('F', 'Fija'), ('V', 'Variable')], help_text='F si es Fija, V si es Variable', max_length=1),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='titulo_deuda',
            field=models.BooleanField(default=False, help_text='Indicador si está relacionado con un título de deuda pública (1: Sí, 0: No).'),
        ),
        migrations.AlterField(
            model_name='plazofijostock',
            name='valor_contable',
            field=models.DecimalField(decimal_places=0, help_text='Valor contable', max_digits=14),
        ),
    ]
