# Generated by Django 5.1.7 on 2025-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0009_remove_chequepagodiferidostock_con_cotizacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inversionstock",
            name="prevision_desvalorizacion",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Previsión desvalorización",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inversionstock",
            name="valor_financiero",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Valor financiero",
                max_digits=14,
                null=True,
            ),
        ),
    ]
