# Generated by Django 5.1.7 on 2025-08-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0010_alter_inversionstock_prevision_desvalorizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baserequestmodel",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("ENVIADA", "Enviada"),
                    ("RECTIFICANDO", "Rectificando"),
                ],
                default="BORRADOR",
                help_text="Estado de la solicitud (Borrador, Enviada, Rectificando)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="baserequestmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
