# Generated by Django 5.1.7 on 2025-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0011_baserequestmodel_estado_baserequestmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="canjeoperacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AddField(
            model_name="compraoperacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AddField(
            model_name="plazofijooperacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AddField(
            model_name="ventaoperacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Última Modificación"
            ),
        ),
    ]
