# Generated by Django 5.1.7 on 2025-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operaciones",
            "0012_canjeoperacion_updated_at_compraoperacion_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="canjeoperacion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AddField(
            model_name="compraoperacion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AddField(
            model_name="ventaoperacion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
    ]
