# Generated by Django 5.1.7 on 2025-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operaciones",
            "0013_canjeoperacion_created_at_compraoperacion_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plazofijooperacion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
    ]
