# Generated by Django 5.1.7 on 2025-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_plazofijooperacion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraoperacion',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, help_text='Precio de compra', max_digits=8),
        ),
    ]
